name: 'Terraform'

on:
  push:
    branches: [ "master" ]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: actions

    env:
      AWS_ACCESS_KEY_ID: "AKIAZDZTBWAIN4MRKBEV"
      AWS_SECRET_ACCESS_KEY: "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"
      AWS_DEFAULT_REGION: us-east-2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false